---
title: "Data Preprocessing"
output:
  word_document: default
  html_document: default
  pdf_document: default
date: "2026-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

## Step 1: install and load necessary packages and libraries

```{r}
#install.packages("caret")

library(readxl)
library(dplyr)
library(tidyr)
library(caret)
```

## Step 2: Load dataset and check for missing values

```{r}
health_data <- read_excel("Case Study Dataset - Insurance Costs.xlsx")
summary(health_data)
str(health_data)

# Check number of missing values
sum(is.na(health_data))
```

## Step 3: One hot encode categorical variables
```{r}
categorical_columns <- sapply(health_data, is.character)

# Extract the original data without categorical columns
original_data <- health_data[,!categorical_columns]

# Create dummy variables only for the categorical columns
dummy_vars <- dummyVars(paste("~ .", collapse = " + "), 
                        data = health_data[, categorical_columns])
dummy_vars_data <- predict(dummy_vars, health_data[, categorical_columns])

# Bind the original data with the dummy variables
health_data_encoded <- cbind(original_data, dummy_vars_data)
head(health_data_encoded)
```

# Step 4: Save encoded dataset as csv file
```{r}
write.csv(health_data_encoded, "full_data_processed.csv", row.names = FALSE)
```