# -*- coding: utf-8 -*-
"""eda_ydata_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEmWRtYIZOayp7oG3D7E9kzg2OUOhZmt

## Case Study: Analysis of Health-Related Factors and Their Impact on Medical Insurance Costs

### Exploratory Data Analysis (EDA) using ydata_profiling in Python
"""

!pip install ydata-profiling

# Import libraries
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

# Libraries for visualisation
import seaborn as sb
import matplotlib.pyplot as plt
from matplotlib import style

# Load data
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/insurance_costs_dataset.csv', sep=',')

# Generate the report
profile = ProfileReport(df,title="Health-Related Factors and Their Impact on Medical Insurance Costs")

# Save the report to .html
profile.to_file("insurance_costs_eda.html")