# -*- coding: utf-8 -*-
"""eda_scatter_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxeI4jyfzjOgT91uUkuR4hZkWWTH57sf

## Case Study: Analysis of Health-Related Factors and Their Impact on Medical Insurance Costs

### EDA: Scatter Plots of Medical Insurance Charges vs Health Related Factors
"""

# import modules and libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load Data
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data-files/insurance_costs_dataset.csv', sep =',')
df

"""#### Plots for age, bmi, number of children, and sex of policyholder"""

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, layout='constrained')
ax1.scatter(df['age'], df['charges'], color ='orange')
ax1.set(xlabel='age',ylabel='charges')
ax2.scatter(df['bmi'], df['charges'], color ='green')
ax2.set(xlabel='bmi',ylabel='charges')
ax3.scatter(df['children'], df['charges'], color = 'purple')
ax3.set(xlabel='children', ylabel='charges')
ax4.scatter(df['sex'], df['charges'], color = 'blue')
ax4.set(xlabel='sex', ylabel='charges')

plt.show()

"""#### Plots for region and smoker status of policyholder"""

# Rename region categories
df['region'] = df['region'].astype('category')
df['region'] = df['region'].cat.rename_categories({'southwest': 'SW', 'southeast': 'SE', 'northwest': 'NW', 'northeast': 'NE'})

# Plot
fig, (ax1, ax2) = plt.subplots(1, 2, layout='constrained')
ax1.scatter(df['region'], df['charges'], color ='orange')
ax1.set(xlabel='region',ylabel='charges')
ax2.scatter(df['smoker'], df['charges'], color ='green')
ax2.set(xlabel='smoker',ylabel='charges')


plt.show()